/* Generated By:JavaCC: Do not edit this line. ParserPrologConstants.java */
package uniandes.teolen.parserJavaCC.parserProlog;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserPrologConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ARROW = 5;
  /** RegularExpression Id. */
  int INT = 6;
  /** RegularExpression Id. */
  int DIGIT = 7;
  /** RegularExpression Id. */
  int MAY = 8;
  /** RegularExpression Id. */
  int MIN = 9;
  /** RegularExpression Id. */
  int VAR = 10;
  /** RegularExpression Id. */
  int NOMB = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\":-\"",
    "<INT>",
    "<DIGIT>",
    "<MAY>",
    "<MIN>",
    "<VAR>",
    "<NOMB>",
    "\",\"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"|\"",
    "\"]\"",
  };

}
