// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/Mult4.gold"
import gold.structures.automaton.*;
import gold.structures.map.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class Mult4 {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=7;
      Object m=$fix(Mult4.createTransducer());
      $line=9;
      Utilities.test($cast(gold.structures.automaton.IAutomaton.class,m),$cast(java.lang.String.class,"$"),$cast(java.lang.Boolean.class,true));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Mult4.class,"main",$line);
    }
  }
  public static ITransducer createTransducer() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=15;
      Object Q=$fix($opUnionY(GCollections.asSet(0,1,2,3,"f","I","e"),$opCartsY(new Object[]{GCollections.asSet("R"),GCollections.asSet(0,1,2,3)})));
      $line=17;
      Object \u03A3=$fix($opUnionY($opIntvlY('0','9'),GCollections.asSet('$','R')));
      $line=18;
      Object Out=$fix($opUnionY($opIntvlY('0','9'),GCollections.asSet('$')));
      $line=20;
      Object q_0=$fix("I");
      $line=21;
      Object F=$fix(GCollections.asSet("f"));
      $line=22;
      $result=$invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,Out,q_0,F,new GMethod(Mult4.class,"\u03B4"),new GMethod(Mult4.class,"g"),new GMethod(Mult4.class,"h")});
      if (true) break $try;
      $line=23;
      $rethrow(new RuntimeException("The function \"createTransducer()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Mult4.class,"createTransducer",$line);
    }
    return $cast(ITransducer.class,$result);
  }
  public static Object \u03B4(Object q, Object s) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=26;
      Object d=$fix($opSubtrY(s,'0'));
      $line=27;
      if ($opMembrY(q,GCollections.asSet("f","e"))) {
        $line=28;
        $result="e";
        if (true) break $try;
      }
      else {
        $line=29;
        if (($opEqualY(q,"I")&&$opMembrY(s,$opIntvlY('0','3')))) {
          $line=30;
          $result=GCollections.asList("R",d);
          if (true) break $try;
        }
        else {
          $line=31;
          if ($opEqualY(q,"I")) {
            $line=32;
            $result="e";
            if (true) break $try;
          }
          else {
            $line=33;
            if (($opMembrY(q,$opIntvlY(0,3))&&$opEqualY(s,'$'))) {
              $line=34;
              $result="f";
              if (true) break $try;
            }
            else {
              $line=35;
              if (($opMembrY(q,$opIntvlY(0,3))&&$opMembrY(s,$opIntvlY('0','9')))) {
                $line=36;
                $result=$opQuotnY($opAdditY($opMultpY(4,d),q),10);
                if (true) break $try;
              }
              else {
                $line=38;
                $result="e";
                if (true) break $try;
              }
            }
          }
        }
      }
      $line=40;
      $rethrow(new RuntimeException("The function \"\u03B4(q:Object,s:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Mult4.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object \u03B4(java.lang.Iterable $v1, Object x) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v2=GCollections.unmodifiableCollection($v1).iterator();
      Object r=$v2.next();
      Object s=$v2.next();
      $line=43;
      if ($opEqualY(x,'R')) {
        $line=43;
        $result=s;
        if (true) break $try;
      }
      else {
        $line=44;
        $result="e";
        if (true) break $try;
      }
      $line=46;
      $rethrow(new RuntimeException("The function \"\u03B4(\u27E8r,s\u27E9:java.lang.Iterable,x:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Mult4.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object h(Object q, Object s) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=49;
      Object d=$fix($opSubtrY(s,'0'));
      $line=50;
      if (($opMembrY(q,$opIntvlY(0,4))&&$opMembrY(s,$opIntvlY('0','9')))) {
        $line=51;
        $result=$opModulY($opAdditY($opMultpY(4,d),q),10);
        if (true) break $try;
      }
      else {
        $line=52;
        if (($opMembrY(q,$opIntvlY(0,4))&&$opEqualY(s,'$'))) {
          $line=53;
          $result=(($opEqualY(q,0))?(""):(q));
          if (true) break $try;
        }
        else {
          $line=55;
          $result="";
          if (true) break $try;
        }
      }
      $line=57;
      $rethrow(new RuntimeException("The function \"h(q:Object,s:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Mult4.class,"h",$line);
    }
    return $result;
  }
  public static Object g(Object q) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=62;
      $result="";
      if (true) break $try;
      $line=63;
      $rethrow(new RuntimeException("The function \"g(q:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Mult4.class,"g",$line);
    }
    return $result;
  }
}
