// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/LexerParserRobot202210.gold"
import gold.*;
import gold.structures.*;
import gold.structures.automaton.*;
import gold.structures.bag.*;
import gold.structures.collection.*;
import gold.structures.deque.*;
import gold.structures.disjointset.*;
import gold.structures.graph.*;
import gold.structures.heap.*;
import gold.structures.list.*;
import gold.structures.map.*;
import gold.structures.multimap.*;
import gold.structures.point.*;
import gold.structures.queue.*;
import gold.structures.set.*;
import gold.structures.stack.*;
import gold.structures.tree.*;
import gold.structures.tree.binary.*;
import gold.structures.tree.nary.*;
import gold.structures.tuple.*;
import gold.structures.turingMachine.*;
import gold.swing.*;
import gold.swing.icon.*;
import gold.swing.icon.ajaxload.*;
import gold.swing.icon.famfamfam.*;
import gold.swing.icon.gold.*;
import gold.swing.icon.jlfgr.*;
import gold.swing.icon.wikimedia.*;
import gold.swing.icon.windows.*;
import gold.swing.look.*;
import gold.swing.util.*;
import gold.test.*;
import gold.test.automaton.*;
import gold.test.general.*;
import gold.test.graph.*;
import gold.util.*;
import gold.visualization.*;
import gold.visualization.automaton.*;
import gold.visualization.graph.*;
import gold.visualization.quadtree.*;
import gold.visualization.turingMachine.*;
import gold.visualization.util.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class LexerParserRobot202210 {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static String currentString=null;
  static {
    int $line=0;
    $line=12;
    $try:try {
      currentString=$defaultValue(String.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202210.class,null,$line);
    }
  }
  public static GArrayList images=null;
  static {
    int $line=0;
    $line=13;
    $try:try {
      images=$invokeConstructor(GArrayList.class,new Object[]{});
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202210.class,null,$line);
    }
  }
  public static ISet allSymbols=null;
  static {
    int $line=0;
    $line=15;
    $try:try {
      allSymbols=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202210.class,null,$line);
    }
  }
  public static ISet keyWords=null;
  static {
    int $line=0;
    $line=16;
    $try:try {
      keyWords=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202210.class,null,$line);
    }
  }
  public static ISet skipChars=null;
  static {
    int $line=0;
    $line=17;
    $try:try {
      skipChars=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202210.class,null,$line);
    }
  }
  public static ISet preKW=null;
  static {
    int $line=0;
    $line=19;
    $try:try {
      preKW=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202210.class,null,$line);
    }
  }
  public static ISet preOps=null;
  static {
    int $line=0;
    $line=20;
    $try:try {
      preOps=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202210.class,null,$line);
    }
  }
  public static ISet StartOps=null;
  static {
    int $line=0;
    $line=22;
    $try:try {
      StartOps=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202210.class,null,$line);
    }
  }
  public static ISet Symbols1=null;
  static {
    int $line=0;
    $line=23;
    $try:try {
      Symbols1=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202210.class,null,$line);
    }
  }
  public static ISet CharsSymbols1=null;
  static {
    int $line=0;
    $line=25;
    $try:try {
      CharsSymbols1=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202210.class,null,$line);
    }
  }
  public static ISet alphaUpper=null;
  static {
    int $line=0;
    $line=27;
    $try:try {
      alphaUpper=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202210.class,null,$line);
    }
  }
  public static ISet alphaLower=null;
  static {
    int $line=0;
    $line=28;
    $try:try {
      alphaLower=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202210.class,null,$line);
    }
  }
  public static ISet digits=null;
  static {
    int $line=0;
    $line=29;
    $try:try {
      digits=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202210.class,null,$line);
    }
  }
  public static ISet alphaNum=null;
  static {
    int $line=0;
    $line=31;
    $try:try {
      alphaNum=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202210.class,null,$line);
    }
  }
  public static ISet Out=null;
  static {
    int $line=0;
    $line=33;
    $try:try {
      Out=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202210.class,null,$line);
    }
  }
  public static Boolean diffIdents=null;
  static {
    int $line=0;
    $line=34;
    $try:try {
      diffIdents=$defaultValue(Boolean.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202210.class,null,$line);
    }
  }
  public static ISet Ids=null;
  static {
    int $line=0;
    $line=36;
    $try:try {
      Ids=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202210.class,null,$line);
    }
  }
  public static GHashTableMap translation=null;
  static {
    int $line=0;
    $line=37;
    $try:try {
      translation=$invokeConstructor(GHashTableMap.class,new Object[]{});
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202210.class,null,$line);
    }
  }
  public static Object chars(Object string) {
    int $line=0;
    Object $result=null;
    $try:try {
      gold.structures.set.ISet $v1=$newSet();
      int $v3=$int(0);
      int $v4=$int($invokeMethod("length",string,new Object[]{}))-1;
      $v2:for (int i=$v3; i<=$v4; i++) {
        $v1.add($invokeMethod("charAt",string,new Object[]{i}));
      }
      $result=$v1;
      if (true) break $try;
      $line=38;
      $rethrow(new RuntimeException("The function \"chars(string:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202210.class,"chars",$line);
    }
    return $result;
  }
  public static Object charsStrings(Object strings) {
    int $line=0;
    Object $result=null;
    $try:try {
      gold.structures.set.ISet $v5=$newSet(GCollections.emptySet());
      $v6:for (Object s:GCollections.unmodifiableCollection(strings)) {
        $v5.union(GCollections.unmodifiableSet(((java.lang.Iterable)(LexerParserRobot202210.chars(s)))));
      }
      $result=$v5;
      if (true) break $try;
      $line=39;
      $rethrow(new RuntimeException("The function \"charsStrings(strings:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202210.class,"charsStrings",$line);
    }
    return $result;
  }
  public static Object elements(Object array) {
    int $line=0;
    Object $result=null;
    $try:try {
      gold.structures.set.ISet $v7=$newSet();
      int $v9=$int(0);
      int $v10=$int($opAbsolY(array))-1;
      $v8:for (int i=$v9; i<=$v10; i++) {
        $v7.add($getArrayValue(array,new Object[]{i}));
      }
      $result=$v7;
      if (true) break $try;
      $line=40;
      $rethrow(new RuntimeException("The function \"elements(array:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202210.class,"elements",$line);
    }
    return $result;
  }
  public static Object prefixes(Object string) {
    int $line=0;
    Object $result=null;
    $try:try {
      gold.structures.set.ISet $v11=$newSet();
      int $v13=$int(1);
      int $v14=$int($invokeMethod("length",string,new Object[]{}));
      $v12:for (int i=$v13; i<=$v14; i++) {
        $v11.add($invokeMethod("substring",string,new Object[]{0,i}));
      }
      $result=$v11;
      if (true) break $try;
      $line=41;
      $rethrow(new RuntimeException("The function \"prefixes(string:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202210.class,"prefixes",$line);
    }
    return $result;
  }
  public static Object splits(Object string) {
    int $line=0;
    Object $result=null;
    $try:try {
      gold.structures.set.ISet $v15=$newSet();
      int $v17=$int(1);
      int $v18=$int($opSubtrY($invokeMethod("length",string,new Object[]{}),1));
      $v16:for (int i=$v17; i<=$v18; i++) {
        $v15.add(GCollections.asList($invokeMethod("substring",string,new Object[]{0,i}),$invokeMethod("substring",string,new Object[]{i,$invokeMethod("length",string,new Object[]{})})));
      }
      $result=$v15;
      if (true) break $try;
      $line=42;
      $rethrow(new RuntimeException("The function \"splits(string:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202210.class,"splits",$line);
    }
    return $result;
  }
  public static Object allPrefixes(Object strings) {
    int $line=0;
    Object $result=null;
    $try:try {
      gold.structures.set.ISet $v19=$newSet(GCollections.emptySet());
      $v20:for (Object s:GCollections.unmodifiableCollection(strings)) {
        $v19.union(GCollections.unmodifiableSet(((java.lang.Iterable)(LexerParserRobot202210.prefixes(s)))));
      }
      $result=$v19;
      if (true) break $try;
      $line=43;
      $rethrow(new RuntimeException("The function \"allPrefixes(strings:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202210.class,"allPrefixes",$line);
    }
    return $result;
  }
  public static Object translationGet(Object q) {
    int $line=0;
    Object $result=null;
    $try:try {
      $result=(($bool((($opEqualY($opAbsolY(q),1)&&$opMembrY(q,Symbols1))&&!$opEqualY(q,'\n'))))?(q):(((gold.structures.map.GHashTableMap)translation).get(q)));
      if (true) break $try;
      $line=44;
      $rethrow(new RuntimeException("The function \"translationGet(q:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202210.class,"translationGet",$line);
    }
    return $result;
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=47;
      currentString=$cast(String.class,$fix(""));
      $line=48;
      Object lexer=$fix(LexerParserRobot202210.createLexer());
      $line=49;
      Object parser=$fix(LexerParserRobot202210.createParser());
      $line=51;
      LexerParserRobot202210.testLexer($cast(gold.structures.automaton.ITransducer.class,lexer));
      $line=53;
      LexerParserRobot202210.testLexerParser($cast(gold.structures.automaton.ITransducer.class,lexer),$cast(gold.structures.automaton.IPushdownAutomaton.class,parser));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202210.class,"main",$line);
    }
  }
  public static Object testLexer(ITransducer M) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=57;
      java.util.Scanner sc=null;
      sc=$invokeConstructor(java.util.Scanner.class,new Object[]{$invokeField(System.class,"in",true,null)});
      $line=58;
      String string=null;
      string=$defaultValue(String.class);
      $line=59;
      Object inputA=$fix(LexerParserRobot202210.elements(((gold.structures.automaton.ITransducer)M).getInputAlphabet()));
      $line=60;
      Object input=$fix("");
      $line=62;
      System.out.println($message(new Object[]{"----------------------------"}));
      $line=63;
      System.out.println($message(new Object[]{"Enter one or more lines. End with a single line with $"}));
      $line=64;
      System.out.println($message(new Object[]{"If you want to stop testing, enter EXIT"}));
      $line=65;
      string=$cast(String.class,$fix(((java.util.Scanner)sc).nextLine()));
      $line=67;
      while (true) {
        if (!(!$opEqualY(string,"EXIT"))) break;
        $line=68;
        string=$cast(String.class,$fix($opAdditY(string," \n ")));
        $line=69;
        input=$fix("");
        $line=70;
        while (true) {
          if (!(!$opEqualY(((java.lang.String)string).charAt($int(0)),'$'))) break;
          $line=71;
          input=$fix($opAdditY(input,string));
          $line=72;
          string=$cast(String.class,$fix($opAdditY(((java.util.Scanner)sc).nextLine()," \n  ")));
        }
        $line=75;
        if ($opSbsetY(LexerParserRobot202210.chars(input),inputA)) {
          $line=76;
          currentString=$cast(String.class,$fix(""));
          $line=77;
          images=$cast(GArrayList.class,$fix($invokeConstructor(GArrayList.class,new Object[]{})));
          $line=78;
          Object result=$fix(((gold.structures.automaton.ITransducer)M).acceptsString($cast(java.lang.String.class,input)));
          $line=79;
          Object tokenStream=$fix(((gold.structures.automaton.ITransducer)M).getOutputString());
          $line=81;
          System.out.println($message(new Object[]{$opAdditY($opAdditY("The input was ",(($bool(result))?(""):("not ")))," accepted by the lexer.")}));
          $line=82;
          if ($bool(result)) {
            $line=83;
            System.out.println($message(new Object[]{$opAdditY("Token Stream:  ",tokenStream)}));
            $line=84;
            System.out.println($message(new Object[]{$opAdditY("Strings: ",images)}));
          }
          else {
            $line=86;
            System.out.println($message(new Object[]{$opAdditY("Partial token Stream ",tokenStream)}));
          }
        }
        else {
          $line=89;
          System.out.println($message(new Object[]{$opAdditY("Input contains invalid characters: ",$opDiffeY(LexerParserRobot202210.chars(input),inputA))}));
        }
        $line=91;
        System.out.println($message(new Object[]{"----------------------------"}));
        $line=93;
        System.out.println($message(new Object[]{"Enter one or more lines. End with a single line with $"}));
        $line=94;
        System.out.println($message(new Object[]{"If you want to stop testing, enter EXIT"}));
        $line=95;
        string=$cast(String.class,$fix(((java.util.Scanner)sc).nextLine()));
      }
      $line=97;
      System.out.println($message(new Object[]{"Good bye"}));
      $line=98;
      System.out.println($message(new Object[]{""}));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202210.class,"testLexer",$line);
    }
    return $result;
  }
  public static Object problems(String q) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=103;
      if ($opMembrY(q,allSymbols)) {
        $line=104;
        $result=false;
        if (true) break $try;
      }
      else {
        $line=105;
        if ($opLessqY($opAbsolY(q),1)) {
          $line=106;
          $result=true;
          if (true) break $try;
        }
        else {
          $line=108;
          for (Object $v21:GCollections.unmodifiableCollection(LexerParserRobot202210.splits(q))) {
            java.util.Iterator $v22=GCollections.unmodifiableCollection($v21).iterator();
            Object s=$v22.next();
            Object t=$v22.next();
            $line=109;
            if ((!$bool(LexerParserRobot202210.problems($cast(java.lang.String.class,s)))&&!$bool(LexerParserRobot202210.problems($cast(java.lang.String.class,t))))) {
              $line=110;
              $result=false;
              if (true) break $try;
            }
          }
          $line=113;
          $result=true;
          if (true) break $try;
        }
      }
      $line=115;
      $rethrow(new RuntimeException("The function \"problems(q:String)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202210.class,"problems",$line);
    }
    return $result;
  }
  public static Object translationPreOps(Object state) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=118;
      Object x=null;
      Object y=null;
      $line=119;
      String q=null;
      q=$defaultValue(String.class);
      $line=120;
      q=$cast(String.class,$fix(state));
      $line=121;
      Object n=$fix(((java.lang.String)q).length());
      $line=122;
      if ($opEqualY(n,0)) {
        $line=123;
        $result="";
        if (true) break $try;
      }
      else {
        $line=124;
        if ($opMembrY(q,allSymbols)) {
          $line=125;
          ((gold.structures.list.GArrayList)images).add(q);
          $line=126;
          $result=LexerParserRobot202210.translationGet(q);
          if (true) break $try;
        }
        else {
          $line=127;
          if ($opEqualY(n,1)) {
            $line=128;
            $result="";
            if (true) break $try;
          }
          else {
            $line=130;
            for (Object $v23:GCollections.unmodifiableCollection(LexerParserRobot202210.splits(q))) {
              java.util.Iterator $v24=GCollections.unmodifiableCollection($v23).iterator();
              Object s=$v24.next();
              Object t=$v24.next();
              $line=131;
              x=$fix(LexerParserRobot202210.translationPreOps(s));
              $line=132;
              y=$fix(LexerParserRobot202210.translationPreOps(t));
              $line=133;
              if ((!$opEqualY(x,"")&&!$opEqualY(y,""))) {
                $line=134;
                $result=$opAdditY(x,y);
                if (true) break $try;
              }
            }
            $line=137;
            $result="";
            if (true) break $try;
          }
        }
      }
      $line=139;
      $rethrow(new RuntimeException("The function \"translationPreOps(state:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202210.class,"translationPreOps",$line);
    }
    return $result;
  }
  public static Object initialize() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=142;
      skipChars=$cast(ISet.class,$fix(GCollections.asSet(' ','\t','\n')));
      $line=143;
      alphaUpper=$cast(ISet.class,$fix($opIntvlY('A','Z')));
      $line=144;
      alphaLower=$cast(ISet.class,$fix($opIntvlY('a','z')));
      $line=145;
      digits=$cast(ISet.class,$fix($opIntvlY('0','9')));
      $line=146;
      alphaNum=$cast(ISet.class,$fix($opUnionY($opUnionY($opUnionY(alphaUpper,alphaLower),digits),GCollections.asSet('-'))));
      $line=147;
      keyWords=$cast(ISet.class,$fix(GCollections.asSet(":north",":south",":east",":west",":front",":back",":right",":left",":around",":balloons",":chips","=","defvar","move","turn","face","put","pick","move-dir","run-dirs","move-face","skip","if","loop","repeat","defun","facing-p","can-put-p","can-pick-p","can-move-p","not")));
      $line=157;
      allSymbols=$cast(ISet.class,$fix(GCollections.asSet("(",")")));
      $line=162;
      ((gold.structures.map.GHashTableMap)translation).put(":north",'N');
      $line=163;
      ((gold.structures.map.GHashTableMap)translation).put(":south",'S');
      $line=164;
      ((gold.structures.map.GHashTableMap)translation).put(":east",'E');
      $line=165;
      ((gold.structures.map.GHashTableMap)translation).put(":west",'W');
      $line=166;
      ((gold.structures.map.GHashTableMap)translation).put(":front",'F');
      $line=167;
      ((gold.structures.map.GHashTableMap)translation).put(":back",'B');
      $line=168;
      ((gold.structures.map.GHashTableMap)translation).put(":right",'R');
      $line=169;
      ((gold.structures.map.GHashTableMap)translation).put(":left",'L');
      $line=170;
      ((gold.structures.map.GHashTableMap)translation).put(":around",'A');
      $line=172;
      ((gold.structures.map.GHashTableMap)translation).put(":balloons",'b');
      $line=173;
      ((gold.structures.map.GHashTableMap)translation).put(":chips",'c');
      $line=175;
      ((gold.structures.map.GHashTableMap)translation).put("defvar",'D');
      $line=176;
      ((gold.structures.map.GHashTableMap)translation).put("=",'=');
      $line=177;
      ((gold.structures.map.GHashTableMap)translation).put("move",'M');
      $line=178;
      ((gold.structures.map.GHashTableMap)translation).put("turn",'T');
      $line=179;
      ((gold.structures.map.GHashTableMap)translation).put("face",'f');
      $line=180;
      ((gold.structures.map.GHashTableMap)translation).put("put",'P');
      $line=181;
      ((gold.structures.map.GHashTableMap)translation).put("pick",'p');
      $line=182;
      ((gold.structures.map.GHashTableMap)translation).put("move-dir",'m');
      $line=183;
      ((gold.structures.map.GHashTableMap)translation).put("run-dirs",'d');
      $line=184;
      ((gold.structures.map.GHashTableMap)translation).put("move-face",'V');
      $line=185;
      ((gold.structures.map.GHashTableMap)translation).put("skip",'s');
      $line=187;
      ((gold.structures.map.GHashTableMap)translation).put("if",'I');
      $line=188;
      ((gold.structures.map.GHashTableMap)translation).put("loop",'l');
      $line=189;
      ((gold.structures.map.GHashTableMap)translation).put("repeat",'r');
      $line=190;
      ((gold.structures.map.GHashTableMap)translation).put("defun",'f');
      $line=192;
      ((gold.structures.map.GHashTableMap)translation).put("facing-p",'i');
      $line=193;
      ((gold.structures.map.GHashTableMap)translation).put("can-put-p",'U');
      $line=194;
      ((gold.structures.map.GHashTableMap)translation).put("can-pick-p",'K');
      $line=195;
      ((gold.structures.map.GHashTableMap)translation).put("can-move-p",'O');
      $line=196;
      ((gold.structures.map.GHashTableMap)translation).put("not",'n');
      $line=198;
      ((gold.structures.map.GHashTableMap)translation).put("IdL",'v');
      $line=199;
      ((gold.structures.map.GHashTableMap)translation).put("IdU",'V');
      $line=200;
      ((gold.structures.map.GHashTableMap)translation).put("Num",'#');
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202210.class,"initialize",$line);
    }
    return $result;
  }
  public static ITransducer createLexer() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=204;
      LexerParserRobot202210.initialize();
      $line=206;
      preOps=$cast(ISet.class,$fix(LexerParserRobot202210.allPrefixes(allSymbols)));
      $line=207;
      preKW=$cast(ISet.class,$fix(LexerParserRobot202210.allPrefixes(keyWords)));
      $line=209;
      gold.structures.set.ISet $v25=$newSet(GCollections.emptySet());
      $v26:for (Object x:GCollections.unmodifiableCollection(allSymbols)) {
        $v25.union(GCollections.unmodifiableSet(((java.lang.Iterable)(GCollections.asSet($invokeMethod("charAt",x,new Object[]{0}))))));
      }
      StartOps=$cast(ISet.class,$fix($v25));
      $line=210;
      gold.structures.set.ISet $v27=$newSet(GCollections.emptySet());
      $v28:for (Object x:GCollections.unmodifiableCollection(StartOps)) {
        $v27.union(GCollections.unmodifiableSet(((java.lang.Iterable)(GCollections.asSet($opAdditY("",x))))));
      }
      Symbols1=$cast(ISet.class,$fix($opInterY($v27,allSymbols)));
      $line=211;
      gold.structures.set.ISet $v29=$newSet(GCollections.emptySet());
      $v30:for (Object x:GCollections.unmodifiableCollection(Symbols1)) {
        $v29.union(GCollections.unmodifiableSet(((java.lang.Iterable)(GCollections.asSet($invokeMethod("charAt",x,new Object[]{0}))))));
      }
      CharsSymbols1=$cast(ISet.class,$fix($v29));
      $line=213;
      gold.structures.set.ISet $v31=$newSet(GCollections.emptySet());
      $v32:for (Object x:GCollections.unmodifiableCollection(((gold.structures.map.GHashTableMap)translation).values())) {
        $v31.union(GCollections.unmodifiableSet(((java.lang.Iterable)(GCollections.asSet(x)))));
      }
      Out=$cast(ISet.class,$fix($opUnionY(CharsSymbols1,$v31)));
      $line=215;
      System.out.println($message(new Object[]{Out}));
      $line=217;
      Ids=$cast(ISet.class,$fix(GCollections.asSet("IdU","IdL")));
      $line=218;
      Object Q=$fix($opUnionY($opUnionY(GCollections.asSet("INIT","IdU","Num","Err","IdL"),preKW),preOps));
      $line=220;
      System.out.println($message(new Object[]{Q}));
      $line=222;
      Object \u03A3=$fix($opUnionY($opUnionY($opUnionY(alphaNum,LexerParserRobot202210.charsStrings(allSymbols)),skipChars),GCollections.asSet(':','-')));
      $line=224;
      Object q_0=$fix("INIT");
      $line=225;
      Object F=$fix(GCollections.asSet("INIT"));
      $line=227;
      $result=$invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,Out,q_0,F,new GMethod(LexerParserRobot202210.class,"\u03B4"),new GMethod(LexerParserRobot202210.class,"g"),new GMethod(LexerParserRobot202210.class,"h")});
      if (true) break $try;
      $line=228;
      $rethrow(new RuntimeException("The function \"createLexer()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202210.class,"createLexer",$line);
    }
    return $cast(ITransducer.class,$result);
  }
  public static Object \u03B4(Object state, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=231;
      String q=null;
      q=$defaultValue(String.class);
      $line=232;
      q=$cast(String.class,$fix(state));
      $line=234;
      if ($opEqualY(q,"Err")) {
        $line=235;
        $result="Err";
        if (true) break $try;
      }
      else {
        $line=236;
        if ($opMembrY(q,preOps)) {
          $line=237;
          if ($opMembrY($opAdditY(q,\u03C3),preOps)) {
            $line=238;
            $result=$opAdditY(q,\u03C3);
            if (true) break $try;
          }
          else {
            $line=239;
            if ($bool(LexerParserRobot202210.problems($cast(java.lang.String.class,q)))) {
              $line=240;
              $result="Err";
              if (true) break $try;
            }
            else {
              $line=241;
              if ($opMembrY(\u03C3,skipChars)) {
                $line=242;
                $result="INIT";
                if (true) break $try;
              }
              else {
                $line=243;
                if ($opMembrY(\u03C3,$opIntvlY('0','9'))) {
                  $line=244;
                  $result="Num";
                  if (true) break $try;
                }
                else {
                  $line=245;
                  if ($opMembrY($opAdditY("",\u03C3),preKW)) {
                    $line=246;
                    $result=$opAdditY("",\u03C3);
                    if (true) break $try;
                  }
                  else {
                    $line=247;
                    if ($opMembrY(\u03C3,alphaUpper)) {
                      $line=248;
                      $result="IdU";
                      if (true) break $try;
                    }
                    else {
                      $line=249;
                      if ($opMembrY(\u03C3,alphaLower)) {
                        $line=250;
                        $result="IdL";
                        if (true) break $try;
                      }
                      else {
                        $line=251;
                        if ($opMembrY($opAdditY("",\u03C3),preOps)) {
                          $line=252;
                          $result=$opAdditY("",\u03C3);
                          if (true) break $try;
                        }
                        else {
                          $line=254;
                          $result="Err";
                          if (true) break $try;
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        else {
          $line=256;
          if (((($opMembrY(\u03C3,skipChars)&&$opMembrY(q,preKW))&&!$bool($opMembrY(q,keyWords)))&&$opEqualY(((java.lang.String)q).charAt($int(0)),':'))) {
            $line=257;
            $result="Err";
            if (true) break $try;
          }
          else {
            $line=258;
            if ($opMembrY(\u03C3,skipChars)) {
              $line=259;
              $result="INIT";
              if (true) break $try;
            }
            else {
              $line=260;
              if (($opEqualY(q,"INIT")&&$opMembrY(\u03C3,$opIntvlY('0','9')))) {
                $line=261;
                $result="Num";
                if (true) break $try;
              }
              else {
                $line=262;
                if (($opEqualY(q,"INIT")&&$opMembrY($opAdditY("",\u03C3),preKW))) {
                  $line=263;
                  $result=$opAdditY("",\u03C3);
                  if (true) break $try;
                }
                else {
                  $line=264;
                  if (($opEqualY(q,"INIT")&&$opMembrY(\u03C3,alphaUpper))) {
                    $line=265;
                    $result="IdU";
                    if (true) break $try;
                  }
                  else {
                    $line=266;
                    if (($opEqualY(q,"INIT")&&$opMembrY(\u03C3,alphaLower))) {
                      $line=267;
                      $result="IdL";
                      if (true) break $try;
                    }
                    else {
                      $line=268;
                      if (($opEqualY(q,"INIT")&&$opMembrY($opAdditY("",\u03C3),preOps))) {
                        $line=269;
                        $result=$opAdditY("",\u03C3);
                        if (true) break $try;
                      }
                      else {
                        $line=270;
                        if (($opMembrY(q,preKW)&&$opMembrY($opAdditY(q,\u03C3),preKW))) {
                          $line=271;
                          $result=$opAdditY(q,\u03C3);
                          if (true) break $try;
                        }
                        else {
                          $line=272;
                          if ((($opMembrY(q,preKW)&&$opMembrY(\u03C3,alphaNum))&&$opMembrY(((java.lang.String)q).charAt($int(0)),alphaUpper))) {
                            $line=273;
                            $result="IdU";
                            if (true) break $try;
                          }
                          else {
                            $line=274;
                            if ((($opMembrY(q,preKW)&&$opMembrY(\u03C3,alphaNum))&&$opMembrY(((java.lang.String)q).charAt($int(0)),alphaLower))) {
                              $line=275;
                              $result="IdL";
                              if (true) break $try;
                            }
                            else {
                              $line=276;
                              if (($opMembrY(q,preKW)&&$opMembrY($opAdditY("",\u03C3),preOps))) {
                                $line=277;
                                $result=$opAdditY("",\u03C3);
                                if (true) break $try;
                              }
                              else {
                                $line=278;
                                if (($opEqualY(q,"Num")&&$opMembrY(\u03C3,$opIntvlY('0','9')))) {
                                  $line=279;
                                  $result="Num";
                                  if (true) break $try;
                                }
                                else {
                                  $line=280;
                                  if (($opEqualY(q,"Num")&&$opMembrY($opAdditY("",\u03C3),preOps))) {
                                    $line=281;
                                    $result=$opAdditY("",\u03C3);
                                    if (true) break $try;
                                  }
                                  else {
                                    $line=282;
                                    if (($opEqualY(q,"Num")&&$opMembrY(\u03C3,alphaNum))) {
                                      $line=283;
                                      $result="Err";
                                      if (true) break $try;
                                    }
                                    else {
                                      $line=284;
                                      if (($opMembrY(q,Ids)&&$opMembrY(\u03C3,alphaNum))) {
                                        $line=285;
                                        $result=q;
                                        if (true) break $try;
                                      }
                                      else {
                                        $line=286;
                                        if (($opMembrY(q,Ids)&&$opMembrY($opAdditY("",\u03C3),preOps))) {
                                          $line=287;
                                          $result=$opAdditY("",\u03C3);
                                          if (true) break $try;
                                        }
                                        else {
                                          $line=289;
                                          $result="Err";
                                          if (true) break $try;
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=291;
      $rethrow(new RuntimeException("The function \"\u03B4(state:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202210.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object g(Object q) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=294;
      $result="";
      if (true) break $try;
      $line=295;
      $rethrow(new RuntimeException("The function \"g(q:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202210.class,"g",$line);
    }
    return $result;
  }
  public static Object h(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=298;
      String s=null;
      s=$defaultValue(String.class);
      $line=300;
      s=$cast(String.class,$fix((($bool($opEqualY(\u03C3,'\n')))?("\\n"):($opAdditY("",\u03C3)))));
      $line=302;
      if ($opMembrY(q,preOps)) {
        $line=303;
        if (($opMembrY(\u03C3,skipChars)&&$opMembrY(q,allSymbols))) {
          $line=304;
          ((gold.structures.list.GArrayList)images).add(currentString);
          $line=305;
          currentString=$cast(String.class,$fix(""));
          $line=306;
          $result=LexerParserRobot202210.translationGet(q);
          if (true) break $try;
        }
        else {
          $line=307;
          if ($opMembrY($opAdditY(q,\u03C3),preOps)) {
            $line=308;
            currentString=$cast(String.class,$fix($opAdditY(currentString,s)));
            $line=309;
            $result="";
            if (true) break $try;
          }
          else {
            $line=310;
            if (($opMembrY(\u03C3,$opUnionY(StartOps,alphaNum))&&$opMembrY(q,allSymbols))) {
              $line=311;
              ((gold.structures.list.GArrayList)images).add(currentString);
              $line=312;
              currentString=$cast(String.class,$fix($opAdditY("",s)));
              $line=313;
              $result=LexerParserRobot202210.translationGet(q);
              if (true) break $try;
            }
            else {
              $line=314;
              if ($opMembrY(\u03C3,$opUnionY($opUnionY(StartOps,alphaNum),skipChars))) {
                $line=315;
                currentString=$cast(String.class,$fix($opAdditY("",s)));
                $line=316;
                $result=LexerParserRobot202210.translationPreOps(q);
                if (true) break $try;
              }
              else {
                $line=318;
                currentString=$cast(String.class,$fix($opAdditY(currentString,s)));
                $line=319;
                $result="";
                if (true) break $try;
              }
            }
          }
        }
      }
      else {
        $line=322;
        if ((!$opMembrY(q,GCollections.asSet("Err"))&&$opMembrY(\u03C3,$opUnionY(skipChars,StartOps)))) {
          $line=323;
          if ($opEqualY(q,"INIT")) {
            $line=324;
            currentString=$cast(String.class,$fix((($bool($opMembrY(\u03C3,StartOps)))?(s):(""))));
            $line=325;
            $result="";
            if (true) break $try;
          }
          else {
            $line=326;
            if ($opEqualY(LexerParserRobot202210.translationGet(q),null)) {
              $line=327;
              ((gold.structures.list.GArrayList)images).add(currentString);
              $line=328;
              currentString=$cast(String.class,$fix((($bool($opMembrY(\u03C3,$opUnionY(skipChars,StartOps))))?(s):(""))));
              $line=329;
              Object f=$fix($invokeMethod("charAt",q,new Object[]{0}));
              $line=330;
              if ($opMembrY(f,alphaUpper)) {
                $line=331;
                $result=LexerParserRobot202210.translationGet("IdU");
                if (true) break $try;
              }
              else {
                $line=332;
                if ($opMembrY(f,alphaLower)) {
                  $line=333;
                  $result=LexerParserRobot202210.translationGet("IdL");
                  if (true) break $try;
                }
                else {
                  $line=335;
                  $result=null;
                  if (true) break $try;
                }
              }
            }
            else {
              $line=338;
              ((gold.structures.list.GArrayList)images).add(currentString);
              $line=339;
              currentString=$cast(String.class,$fix((($bool($opMembrY(\u03C3,$opUnionY(skipChars,StartOps))))?(s):(""))));
              $line=340;
              $result=LexerParserRobot202210.translationGet(q);
              if (true) break $try;
            }
          }
        }
        else {
          $line=343;
          currentString=$cast(String.class,$fix($opAdditY(currentString,s)));
          $line=344;
          $result="";
          if (true) break $try;
        }
      }
      $line=346;
      $rethrow(new RuntimeException("The function \"h(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202210.class,"h",$line);
    }
    return $result;
  }
  public static IPushdownAutomaton createParser() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=350;
      Object Q=$fix($opIntvlY(0,6));
      $line=351;
      Object \u03A3=$fix(Out);
      $line=352;
      Object \u0393=$fix(GCollections.asSet('1','D','=','M','T','f','P','p','m','d','V','s','c','I','l','r','f','e','U','K','O','n'));
      $line=358;
      Object q_0=$fix(0);
      $line=359;
      Object F=$fix(GCollections.asSet(0));
      $line=361;
      Object M=$fix($invokeConstructor(GPushdownAutomaton.class,new Object[]{Q,\u03A3,\u0393,q_0,F}));
      $line=365;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,1,$cast(java.lang.String.class,'(')),new Object[]{"1"});
      $line=366;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,2,$cast(java.lang.String.class,'D')),new Object[]{"D"});
      $line=367;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,3,$cast(java.lang.String.class,'V')),new Object[]{"D"});
      $line=368;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,3,$cast(java.lang.String.class,'v')),new Object[]{"D"});
      $line=369;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(3,4,$cast(java.lang.String.class,'#')),new Object[]{"D"});
      $line=370;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(4,0,$cast(java.lang.String.class,')')),new Object[]{"1DDD"});
      $line=372;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,1,$cast(java.lang.String.class,'(')),new Object[]{"1"});
      $line=373;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,2,$cast(java.lang.String.class,'=')),new Object[]{"="});
      $line=374;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,3,$cast(java.lang.String.class,'V')),new Object[]{"="});
      $line=375;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,3,$cast(java.lang.String.class,'v')),new Object[]{"="});
      $line=376;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(3,4,$cast(java.lang.String.class,'#')),new Object[]{"="});
      $line=377;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(4,0,$cast(java.lang.String.class,')')),new Object[]{"1==="});
      $line=379;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,1,$cast(java.lang.String.class,'(')),new Object[]{"1"});
      $line=380;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,2,$cast(java.lang.String.class,'M')),new Object[]{"M"});
      $line=381;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,4,$cast(java.lang.String.class,'#')),new Object[]{"M"});
      $line=382;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,4,$cast(java.lang.String.class,'V')),new Object[]{"M"});
      $line=383;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,4,$cast(java.lang.String.class,'v')),new Object[]{"M"});
      $line=384;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(4,0,$cast(java.lang.String.class,')')),new Object[]{"1MM"});
      $line=386;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,1,$cast(java.lang.String.class,'(')),new Object[]{"1"});
      $line=387;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,2,$cast(java.lang.String.class,'T')),new Object[]{"T"});
      $line=388;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,4,$cast(java.lang.String.class,'L')),new Object[]{"T"});
      $line=389;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,4,$cast(java.lang.String.class,'R')),new Object[]{"T"});
      $line=390;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,4,$cast(java.lang.String.class,'A')),new Object[]{"T"});
      $line=391;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(4,0,$cast(java.lang.String.class,')')),new Object[]{"1TT"});
      $line=393;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,1,$cast(java.lang.String.class,'(')),new Object[]{"1"});
      $line=394;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,5,$cast(java.lang.String.class,'f')),new Object[]{"f"});
      $line=395;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,4,$cast(java.lang.String.class,'N')),new Object[]{"f"});
      $line=396;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,4,$cast(java.lang.String.class,'S')),new Object[]{"f"});
      $line=397;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,4,$cast(java.lang.String.class,'E')),new Object[]{"f"});
      $line=398;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,4,$cast(java.lang.String.class,'W')),new Object[]{"f"});
      $line=399;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(4,0,$cast(java.lang.String.class,')')),new Object[]{"1ff"});
      $line=401;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,1,$cast(java.lang.String.class,'(')),new Object[]{"1"});
      $line=402;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,2,$cast(java.lang.String.class,'P')),new Object[]{"P"});
      $line=403;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,3,$cast(java.lang.String.class,'b')),new Object[]{"P"});
      $line=404;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,3,$cast(java.lang.String.class,'c')),new Object[]{"P"});
      $line=405;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(3,4,$cast(java.lang.String.class,'#')),new Object[]{"P"});
      $line=406;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(3,4,$cast(java.lang.String.class,'V')),new Object[]{"P"});
      $line=407;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(3,4,$cast(java.lang.String.class,'v')),new Object[]{"P"});
      $line=408;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(4,0,$cast(java.lang.String.class,')')),new Object[]{"1PPP"});
      $line=410;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,1,$cast(java.lang.String.class,'(')),new Object[]{"1"});
      $line=411;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,2,$cast(java.lang.String.class,'p')),new Object[]{"p"});
      $line=412;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,3,$cast(java.lang.String.class,'b')),new Object[]{"p"});
      $line=413;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,3,$cast(java.lang.String.class,'c')),new Object[]{"p"});
      $line=414;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(3,4,$cast(java.lang.String.class,'#')),new Object[]{"p"});
      $line=415;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(3,4,$cast(java.lang.String.class,'V')),new Object[]{"p"});
      $line=416;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(3,4,$cast(java.lang.String.class,'v')),new Object[]{"p"});
      $line=417;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(4,0,$cast(java.lang.String.class,')')),new Object[]{"1ppp"});
      $line=419;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,1,$cast(java.lang.String.class,'(')),new Object[]{"1"});
      $line=420;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,2,$cast(java.lang.String.class,'m')),new Object[]{"m"});
      $line=421;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,6,$cast(java.lang.String.class,'#')),new Object[]{"m"});
      $line=422;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,6,$cast(java.lang.String.class,'V')),new Object[]{"m"});
      $line=423;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,6,$cast(java.lang.String.class,'v')),new Object[]{"m"});
      $line=424;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(6,4,$cast(java.lang.String.class,'F')),new Object[]{"m"});
      $line=425;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(6,4,$cast(java.lang.String.class,'R')),new Object[]{"m"});
      $line=426;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(6,4,$cast(java.lang.String.class,'L')),new Object[]{"m"});
      $line=427;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(6,4,$cast(java.lang.String.class,'B')),new Object[]{"m"});
      $line=428;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(4,0,$cast(java.lang.String.class,')')),new Object[]{"1mmm"});
      $line=430;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,1,$cast(java.lang.String.class,'(')),new Object[]{"1"});
      $line=431;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,3,$cast(java.lang.String.class,'d')),new Object[]{"d"});
      $line=432;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(3,2,$cast(java.lang.String.class,'F')),new Object[]{});
      $line=433;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(3,2,$cast(java.lang.String.class,'R')),new Object[]{});
      $line=434;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(3,2,$cast(java.lang.String.class,'L')),new Object[]{});
      $line=435;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(3,2,$cast(java.lang.String.class,'B')),new Object[]{});
      $line=436;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,0,$cast(java.lang.String.class,')')),new Object[]{"1d"});
      $line=438;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,1,$cast(java.lang.String.class,'(')),new Object[]{"1"});
      $line=439;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,3,$cast(java.lang.String.class,'V')),new Object[]{"V"});
      $line=440;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(3,5,$cast(java.lang.String.class,'#')),new Object[]{"V"});
      $line=441;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(3,5,$cast(java.lang.String.class,'V')),new Object[]{"V"});
      $line=442;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(3,5,$cast(java.lang.String.class,'v')),new Object[]{"V"});
      $line=443;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,4,$cast(java.lang.String.class,'N')),new Object[]{"V"});
      $line=444;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,4,$cast(java.lang.String.class,'S')),new Object[]{"V"});
      $line=445;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,4,$cast(java.lang.String.class,'W')),new Object[]{"V"});
      $line=446;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,4,$cast(java.lang.String.class,'E')),new Object[]{"V"});
      $line=447;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(4,0,$cast(java.lang.String.class,')')),new Object[]{"1VVV"});
      $line=449;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,1,$cast(java.lang.String.class,'(')),new Object[]{"1"});
      $line=450;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,4,$cast(java.lang.String.class,'s')),new Object[]{"s"});
      $line=451;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(4,0,$cast(java.lang.String.class,')')),new Object[]{"1s"});
      $line=453;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,1,$cast(java.lang.String.class,'(')),new Object[]{"1"});
      $line=454;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,3,$cast(java.lang.String.class,'V')),new Object[]{"c"});
      $line=455;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,3,$cast(java.lang.String.class,'v')),new Object[]{"c"});
      $line=456;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(3,3,$cast(java.lang.String.class,'V')),new Object[]{});
      $line=457;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(3,3,$cast(java.lang.String.class,'v')),new Object[]{});
      $line=458;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(3,3,$cast(java.lang.String.class,'#')),new Object[]{});
      $line=459;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(3,0,$cast(java.lang.String.class,')')),new Object[]{"1c"});
      $line=463;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,1,$cast(java.lang.String.class,'(')),new Object[]{"1"});
      $line=464;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,2,$cast(java.lang.String.class,'I')),new Object[]{"I"});
      $line=466;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(6,0,$cast(java.lang.String.class,'(')),new Object[]{"II"});
      $line=467;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,2,$cast(java.lang.String.class,')')),new Object[]{"I"});
      $line=468;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,0,$cast(java.lang.String.class,'(')),new Object[]{"II"});
      $line=469;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,4,$cast(java.lang.String.class,')')),new Object[]{"I"});
      $line=470;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(4,0,$cast(java.lang.String.class,')')),new Object[]{"1III"});
      $line=472;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,1,$cast(java.lang.String.class,'(')),new Object[]{"1"});
      $line=473;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,2,$cast(java.lang.String.class,'l')),new Object[]{"l"});
      $line=474;
      $invokeMethod("pop",$invokeMethod("delta",M,new Object[]{}),new Object[]{"1"});
      $line=476;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,1,$cast(java.lang.String.class,'(')),new Object[]{"1"});
      $line=478;
      $invokeMethod("pop",$invokeMethod("delta",M,new Object[]{}),new Object[]{"1"});
      $line=480;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,1,$cast(java.lang.String.class,"(")),new Object[]{"1"});
      $line=482;
      $invokeMethod("pop",$invokeMethod("delta",M,new Object[]{}),new Object[]{"1"});
      $line=488;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,4,$cast(java.lang.String.class,'(')),new Object[]{"1"});
      $line=489;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(4,5,$cast(java.lang.String.class,'i')),new Object[]{"i"});
      $line=490;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,2,$cast(java.lang.String.class,'N')),new Object[]{"i"});
      $line=491;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,2,$cast(java.lang.String.class,'S')),new Object[]{"i"});
      $line=492;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,2,$cast(java.lang.String.class,'E')),new Object[]{"i"});
      $line=493;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,2,$cast(java.lang.String.class,'W')),new Object[]{"i"});
      $line=494;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,6,$cast(java.lang.String.class,')')),new Object[]{"1ii"});
      $line=496;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,4,$cast(java.lang.String.class,'(')),new Object[]{"1"});
      $line=497;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(4,5,$cast(java.lang.String.class,'U')),new Object[]{"U"});
      $line=498;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,3,$cast(java.lang.String.class,'c')),new Object[]{"U"});
      $line=499;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,3,$cast(java.lang.String.class,'b')),new Object[]{"U"});
      $line=500;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(3,2,$cast(java.lang.String.class,'#')),new Object[]{"U"});
      $line=501;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(3,2,$cast(java.lang.String.class,'V')),new Object[]{"U"});
      $line=502;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(3,2,$cast(java.lang.String.class,'v')),new Object[]{"U"});
      $line=503;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,6,$cast(java.lang.String.class,')')),new Object[]{"1UUU"});
      $line=505;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,4,$cast(java.lang.String.class,'(')),new Object[]{"1"});
      $line=506;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(4,5,$cast(java.lang.String.class,'K')),new Object[]{"K"});
      $line=507;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,3,$cast(java.lang.String.class,'c')),new Object[]{"K"});
      $line=508;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,3,$cast(java.lang.String.class,'b')),new Object[]{"K"});
      $line=509;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(3,2,$cast(java.lang.String.class,'#')),new Object[]{"K"});
      $line=510;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(3,2,$cast(java.lang.String.class,'V')),new Object[]{"K"});
      $line=511;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(3,2,$cast(java.lang.String.class,'v')),new Object[]{"K"});
      $line=512;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,6,$cast(java.lang.String.class,')')),new Object[]{"1KKK"});
      $line=514;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,4,$cast(java.lang.String.class,'(')),new Object[]{"1"});
      $line=515;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(4,5,$cast(java.lang.String.class,'O')),new Object[]{"O"});
      $line=516;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,2,$cast(java.lang.String.class,'N')),new Object[]{"O"});
      $line=517;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,2,$cast(java.lang.String.class,'S')),new Object[]{"O"});
      $line=518;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,2,$cast(java.lang.String.class,'E')),new Object[]{"O"});
      $line=519;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,2,$cast(java.lang.String.class,'W')),new Object[]{"O"});
      $line=520;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,6,$cast(java.lang.String.class,')')),new Object[]{"1OO"});
      $line=522;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,1,$cast(java.lang.String.class,'(')),new Object[]{"1"});
      $line=523;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,3,$cast(java.lang.String.class,'V')),new Object[]{"fc"});
      $line=524;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,3,$cast(java.lang.String.class,'v')),new Object[]{"fc"});
      $line=525;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(3,3,$cast(java.lang.String.class,'V')),new Object[]{});
      $line=526;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(3,3,$cast(java.lang.String.class,'v')),new Object[]{});
      $line=527;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(3,3,$cast(java.lang.String.class,'#')),new Object[]{});
      $line=528;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(3,6,$cast(java.lang.String.class,')')),new Object[]{"1fc"});
      $line=530;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,5,$cast(java.lang.String.class,'(')),new Object[]{"1"});
      $line=531;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,2,$cast(java.lang.String.class,'n')),new Object[]{"n"});
      $line=533;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(6,6,$cast(java.lang.String.class,')')),new Object[]{"1n"});
      $line=535;
      $result=M;
      if (true) break $try;
      $line=536;
      $rethrow(new RuntimeException("The function \"createParser()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202210.class,"createParser",$line);
    }
    return $cast(IPushdownAutomaton.class,$result);
  }
  public static Object testLexerParser(ITransducer M, IPushdownAutomaton P) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=539;
      java.util.Scanner sc=null;
      sc=$invokeConstructor(java.util.Scanner.class,new Object[]{$invokeField(System.class,"in",true,null)});
      $line=540;
      String string=null;
      string=$defaultValue(String.class);
      $line=541;
      Object inputA=$fix(LexerParserRobot202210.elements(((gold.structures.automaton.ITransducer)M).getInputAlphabet()));
      $line=542;
      Object input=$fix("");
      $line=544;
      System.out.println($message(new Object[]{"----------------------------"}));
      $line=545;
      System.out.println($message(new Object[]{"Enter one or more lines. End with a single line with $"}));
      $line=546;
      System.out.println($message(new Object[]{"If you want to stop testing, enter EXIT"}));
      $line=547;
      string=$cast(String.class,$fix(((java.util.Scanner)sc).nextLine()));
      $line=549;
      while (true) {
        if (!(!$opEqualY(string,"EXIT"))) break;
        $line=550;
        string=$cast(String.class,$fix($opAdditY(string,"  \n ")));
        $line=551;
        input=$fix("");
        $line=552;
        while (true) {
          if (!(!$opEqualY(((java.lang.String)string).charAt($int(0)),'$'))) break;
          $line=553;
          input=$fix($opAdditY(input,string));
          $line=554;
          string=$cast(String.class,$fix($opAdditY(((java.util.Scanner)sc).nextLine()," \n ")));
        }
        $line=557;
        if ($opSbsetY(LexerParserRobot202210.chars(input),inputA)) {
          $line=558;
          currentString=$cast(String.class,$fix(""));
          $line=559;
          images=$cast(GArrayList.class,$fix($invokeConstructor(GArrayList.class,new Object[]{})));
          $line=560;
          Object result=$fix(((gold.structures.automaton.ITransducer)M).acceptsString($cast(java.lang.String.class,input)));
          $line=561;
          Object tokenStream=$fix(((gold.structures.automaton.ITransducer)M).getOutputString());
          $line=563;
          System.out.println($message(new Object[]{$opAdditY($opAdditY("The input was ",(($bool(result))?(""):("not ")))," accepted by the lexer.")}));
          $line=564;
          if ($bool(result)) {
            $line=565;
            System.out.println($message(new Object[]{$opAdditY("Token Stream:  ",tokenStream)}));
            $line=566;
            System.out.println($message(new Object[]{$opAdditY("Strings: ",images)}));
            $line=567;
            result=$fix(((gold.structures.automaton.IPushdownAutomaton)P).acceptsString($cast(java.lang.String.class,tokenStream)));
            $line=568;
            System.out.println($message(new Object[]{$opAdditY("Parser result: ",(($bool(result))?("accepted "):("rejected ")))}));
          }
          else {
            $line=570;
            System.out.println($message(new Object[]{$opAdditY("Partial token Stream ",tokenStream)}));
          }
        }
        else {
          $line=573;
          System.out.println($message(new Object[]{$opAdditY("Input contains invalid characters: ",$opDiffeY(LexerParserRobot202210.chars(input),inputA))}));
        }
        $line=575;
        System.out.println($message(new Object[]{"----------------------------"}));
        $line=577;
        System.out.println($message(new Object[]{"Enter one or more lines. End with a single line with $"}));
        $line=578;
        System.out.println($message(new Object[]{"If you want to stop testing, enter EXIT"}));
        $line=579;
        string=$cast(String.class,$fix(((java.util.Scanner)sc).nextLine()));
      }
      $line=581;
      System.out.println($message(new Object[]{"Good bye"}));
      $line=582;
      System.out.println($message(new Object[]{""}));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202210.class,"testLexerParser",$line);
    }
    return $result;
  }
}
