// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/evenAs.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class evenAs {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=8;
      Object M=$fix($invokeConstructor(GDeterministicAutomaton.class,new Object[]{GCollections.asSet(0,1),$opIntvlY('a','b'),0,GCollections.asSet(0),new GMethod(evenAs.class,"d")}));
      $line=9;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,M));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,evenAs.class,"main",$line);
    }
  }
  public static Object d(Object q, Object x) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=12;
      if ($opEqualY(x,'a')) {
        $line=12;
        $result=$opModulY($opAdditY(q,1),2);
        if (true) break $try;
      }
      else {
        $line=15;
        $result=q;
        if (true) break $try;
      }
      $line=19;
      $rethrow(new RuntimeException("The function \"d(q:Object,x:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,evenAs.class,"d",$line);
    }
    return $result;
  }
}
