// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/Example.gold"
import gold.structures.automaton.*;
import gold.structures.set.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class Example {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=17;
      Object \u03A3=$fix($opIntvlY('a','c'));
      $line=24;
      Object Q=$fix($opUnionY($opCartsY(new Object[]{GCollections.asSet(0,1),$opIntvlY(0,2),GCollections.asSet(true,false)}),GCollections.asSet("err")));
      $line=26;
      Object q_0=$fix(GCollections.asList(0,1,false));
      $line=27;
      Object F=$fix($opCartsY(new Object[]{GCollections.asSet(0),$opIntvlY(0,2),GCollections.asSet(true,false)}));
      $line=29;
      Object M=$fix($invokeConstructor(GDeterministicAutomaton.class,new Object[]{Q,\u03A3,q_0,F,new GMethod(Example.class,"d")}));
      $line=34;
      if ($bool((!$opEqualY($invokeField("length",args),0)&&$opEqualY(((java.lang.String[])args)[$int(0)],"GUI")))) {
        $line=35;
        GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,M));
      }
      else {
        $line=37;
        Utilities.test($cast(gold.structures.automaton.IAutomaton.class,M));
      }
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Example.class,"main",$line);
    }
  }
  public static Object d(Object q, Object x) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=43;
      $result=q;
      if (true) break $try;
      $line=44;
      $rethrow(new RuntimeException("The function \"d(q:Object,x:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Example.class,"d",$line);
    }
    return $result;
  }
  public static Object d(java.lang.Iterable $v1, Object s) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v2=GCollections.unmodifiableCollection($v1).iterator();
      Object As=$v2.next();
      Object pos=$v2.next();
      Object B=$v2.next();
      $line=47;
      if ($opEqualY(s,'a')) {
        $line=47;
        $result=GCollections.asList($opModulY($opAdditY(As,1),2),$opModulY($opAdditY(pos,1),3),false);
        if (true) break $try;
      }
      else {
        $line=48;
        if (($opEqualY(s,'b')&&!$bool(B))) {
          $line=48;
          $result=GCollections.asList(As,$opModulY($opAdditY(pos,1),3),true);
          if (true) break $try;
        }
        else {
          $line=49;
          if (($opEqualY(s,'c')&&!$opEqualY(pos,0))) {
            $line=49;
            $result=GCollections.asList(As,$opModulY($opAdditY(pos,1),3),false);
            if (true) break $try;
          }
          else {
            $line=50;
            $result="err";
            if (true) break $try;
          }
        }
      }
      $line=52;
      $rethrow(new RuntimeException("The function \"d(\u27E8As,pos,B\u27E9:java.lang.Iterable,s:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Example.class,"d",$line);
    }
    return $result;
  }
}
