// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/CodeDecode.gold"
import gold.*;
import gold.structures.*;
import gold.structures.automaton.*;
import gold.structures.bag.*;
import gold.structures.collection.*;
import gold.structures.deque.*;
import gold.structures.disjointset.*;
import gold.structures.graph.*;
import gold.structures.heap.*;
import gold.structures.list.*;
import gold.structures.map.*;
import gold.structures.multimap.*;
import gold.structures.point.*;
import gold.structures.queue.*;
import gold.structures.set.*;
import gold.structures.stack.*;
import gold.structures.tree.*;
import gold.structures.tree.binary.*;
import gold.structures.tree.nary.*;
import gold.structures.tuple.*;
import gold.structures.turingMachine.*;
import gold.swing.*;
import gold.swing.icon.*;
import gold.swing.icon.ajaxload.*;
import gold.swing.icon.famfamfam.*;
import gold.swing.icon.gold.*;
import gold.swing.icon.jlfgr.*;
import gold.swing.icon.wikimedia.*;
import gold.swing.icon.windows.*;
import gold.swing.look.*;
import gold.swing.util.*;
import gold.test.*;
import gold.test.automaton.*;
import gold.test.general.*;
import gold.test.graph.*;
import gold.util.*;
import gold.visualization.*;
import gold.visualization.automaton.*;
import gold.visualization.graph.*;
import gold.visualization.quadtree.*;
import gold.visualization.turingMachine.*;
import gold.visualization.util.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class CodeDecode {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=33;
      java.util.Scanner sc=null;
      sc=$invokeConstructor(java.util.Scanner.class,new Object[]{$invokeField(System.class,"in",true,null)});
      $line=35;
      Object coder=$fix(CodeDecode.createCoder());
      $line=40;
      Utilities.test($cast(gold.structures.automaton.IAutomaton.class,coder));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,CodeDecode.class,"main",$line);
    }
  }
  public static Object g(Object s) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=45;
      $result="";
      if (true) break $try;
      $line=46;
      $rethrow(new RuntimeException("The function \"g(s:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,CodeDecode.class,"g",$line);
    }
    return $result;
  }
  public static Object shiftSymbol(Object symbol, Object shift) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=49;
      Character r=null;
      r=$defaultValue(Character.class);
      $line=50;
      r=$cast(Character.class,$fix($opAdditY('A',$opModulY($opAdditY($opSubtrY(symbol,'a'),shift),26))));
      $line=51;
      $result=r;
      if (true) break $try;
      $line=52;
      $rethrow(new RuntimeException("The function \"shiftSymbol(symbol:Object,shift:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,CodeDecode.class,"shiftSymbol",$line);
    }
    return $result;
  }
  public static ITransducer createCoder() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=56;
      gold.structures.set.ISet $v1=$newSet();
      $v2:for (Object first:GCollections.unmodifiableCollection($opUnionY(GCollections.asSet(0),$opIntvlY('a','z')))) {
        for (Object second:GCollections.unmodifiableCollection($opUnionY(GCollections.asSet(0),$opIntvlY('a','z')))) {
          for (Object half:GCollections.unmodifiableCollection(GCollections.asSet(0,1))) {
            int $v3=$int(0);
            int $v4=$int(3)-1;
            for (int pos=$v3; pos<=$v4; pos++) {
              int $v5=$int(0);
              int $v6=$int(5)-1;
              for (int d=$v5; d<=$v6; d++) {
                for (Object last:GCollections.unmodifiableCollection($opUnionY(GCollections.asSet(0),$opIntvlY('a','z')))) {
                  $v1.add(GCollections.asList(first,second,half,pos,d,last));
                }
              }
            }
          }
        }
      }
      Object Q=$fix($opUnionY($v1,GCollections.asSet('E',"Err")));
      $line=65;
      Object \u03A3=$fix($opUnionY($opIntvlY('a','z'),GCollections.asSet(':','$')));
      $line=66;
      Object \u03A3_=$fix($opUnionY($opUnionY($opUnionY(\u03A3,$opIntvlY('A','Z')),GCollections.asSet('#')),$opIntvlY('0','5')));
      $line=67;
      Object q_0=$fix(GCollections.asList(0,0,0,0,0,0));
      $line=68;
      Object F=$fix(GCollections.asSet('E'));
      $line=70;
      $result=$invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,\u03A3_,q_0,F,new GMethod(CodeDecode.class,"\u03B4"),new GMethod(CodeDecode.class,"g"),new GMethod(CodeDecode.class,"h")});
      if (true) break $try;
      $line=71;
      $rethrow(new RuntimeException("The function \"createCoder()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,CodeDecode.class,"createCoder",$line);
    }
    return $cast(ITransducer.class,$result);
  }
  public static Object \u03B4(Object state, Object input) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=74;
      $result="Err";
      if (true) break $try;
      $line=75;
      $rethrow(new RuntimeException("The function \"\u03B4(state:Object,input:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,CodeDecode.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object \u03B4(java.lang.Iterable $v7, Object input) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v8=GCollections.unmodifiableCollection($v7).iterator();
      Object first=$v8.next();
      Object second=$v8.next();
      Object half=$v8.next();
      Object pos=$v8.next();
      Object d=$v8.next();
      Object last=$v8.next();
      $line=78;
      if ($opEqualY(input,'$')) {
        $line=78;
        $result='E';
        if (true) break $try;
      }
      else {
        $line=79;
        if ($opEqualY(input,':')) {
          $line=80;
          if ($opEqualY(half,0)) {
            $line=80;
            $result=GCollections.asList(first,second,1,pos,d,last);
            if (true) break $try;
          }
          else {
            $line=81;
            $result="Err";
            if (true) break $try;
          }
        }
        else {
          $line=84;
          if ($opEqualY(half,1)) {
            $line=85;
            if (($opEqualY(input,first)||$opEqualY(input,second))) {
              $line=86;
              $result=GCollections.asList(first,second,half,$opModulY($opAdditY(pos,1),3),$opModulY($opAdditY(d,1),5),input);
              if (true) break $try;
            }
            else {
              $line=88;
              $result=GCollections.asList(first,second,half,$opModulY($opAdditY(pos,1),3),d,input);
              if (true) break $try;
            }
          }
          else {
            $line=91;
            if ($opEqualY(first,0)) {
              $line=92;
              $result=GCollections.asList(input,second,half,pos,d,last);
              if (true) break $try;
            }
            else {
              $line=93;
              if ($opEqualY(second,0)) {
                $line=94;
                $result=GCollections.asList(first,input,half,pos,d,last);
                if (true) break $try;
              }
              else {
                $line=96;
                $result="Err";
                if (true) break $try;
              }
            }
          }
        }
      }
      $line=100;
      $rethrow(new RuntimeException("The function \"\u03B4(\u27E8first,second,half,pos,d,last\u27E9:java.lang.Iterable,input:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,CodeDecode.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object h(Object state, Object input) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=103;
      $result="";
      if (true) break $try;
      $line=104;
      $rethrow(new RuntimeException("The function \"h(state:Object,input:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,CodeDecode.class,"h",$line);
    }
    return $result;
  }
  public static Object h(java.lang.Iterable $v9, Object input) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v10=GCollections.unmodifiableCollection($v9).iterator();
      Object first=$v10.next();
      Object second=$v10.next();
      Object half=$v10.next();
      Object pos=$v10.next();
      Object d=$v10.next();
      Object last=$v10.next();
      $line=107;
      if ($opEqualY(input,'$')) {
        $line=107;
        $result=d;
        if (true) break $try;
      }
      else {
        $line=108;
        if ($opEqualY(input,':')) {
          $line=109;
          if ($opEqualY(half,0)) {
            $line=109;
            $result=input;
            if (true) break $try;
          }
          else {
            $line=110;
            $result="";
            if (true) break $try;
          }
        }
        else {
          $line=113;
          if ($opEqualY(half,1)) {
            $line=114;
            if ($opEqualY(input,first)) {
              $line=115;
              $result=second;
              if (true) break $try;
            }
            else {
              $line=116;
              if ($opEqualY(input,second)) {
                $line=117;
                $result=first;
                if (true) break $try;
              }
              else {
                $line=119;
                if ($opEqualY(input,last)) {
                  $line=120;
                  $result='#';
                  if (true) break $try;
                }
                else {
                  $line=121;
                  if ($opEqualY($opModulY($opAdditY(pos,1),3),1)) {
                    $line=122;
                    $result=CodeDecode.shiftSymbol(input,1);
                    if (true) break $try;
                  }
                  else {
                    $line=123;
                    if ($opEqualY($opModulY($opAdditY(pos,1),3),2)) {
                      $line=124;
                      $result=CodeDecode.shiftSymbol(input,0);
                      if (true) break $try;
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=129;
      $result=input;
      if (true) break $try;
      $line=130;
      $rethrow(new RuntimeException("The function \"h(\u27E8first,second,half,pos,d,last\u27E9:java.lang.Iterable,input:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,CodeDecode.class,"h",$line);
    }
    return $result;
  }
}
