/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int T_DEFVAR = 5;
  /** RegularExpression Id. */
  int T_ASSIGN = 6;
  /** RegularExpression Id. */
  int T_MOVE = 7;
  /** RegularExpression Id. */
  int T_TURN = 8;
  /** RegularExpression Id. */
  int T_FACE = 9;
  /** RegularExpression Id. */
  int T_PUT = 10;
  /** RegularExpression Id. */
  int T_PICK = 11;
  /** RegularExpression Id. */
  int T_MOVE_DIR = 12;
  /** RegularExpression Id. */
  int T_RUN_DIRS = 13;
  /** RegularExpression Id. */
  int T_MOVE_FACE = 14;
  /** RegularExpression Id. */
  int T_SKIP = 15;
  /** RegularExpression Id. */
  int T_IF = 16;
  /** RegularExpression Id. */
  int T_LOOP = 17;
  /** RegularExpression Id. */
  int T_REPEAT = 18;
  /** RegularExpression Id. */
  int T_DEFUN = 19;
  /** RegularExpression Id. */
  int T_CONDITION = 20;
  /** RegularExpression Id. */
  int T_OBJ = 21;
  /** RegularExpression Id. */
  int T_BALLOONS = 22;
  /** RegularExpression Id. */
  int T_CHIPS = 23;
  /** RegularExpression Id. */
  int T_DIRECTION_SIMPLE = 24;
  /** RegularExpression Id. */
  int T_DIRECTION = 25;
  /** RegularExpression Id. */
  int T_ORIENTATION = 26;
  /** RegularExpression Id. */
  int LST_DIRECTION = 27;
  /** RegularExpression Id. */
  int NUMBER = 28;
  /** RegularExpression Id. */
  int DIGIT = 29;
  /** RegularExpression Id. */
  int VAR = 30;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"defvar\"",
    "\"=\"",
    "\"move\"",
    "\"turn\"",
    "\"face\"",
    "\"put\"",
    "\"pick\"",
    "\"move-dir\"",
    "\"run-dirs\"",
    "\"move-face\"",
    "\"skip\"",
    "\"if\"",
    "\"loop\"",
    "\"repeat\"",
    "\"defun\"",
    "<T_CONDITION>",
    "<T_OBJ>",
    "\"ballons\"",
    "\"chips\"",
    "<T_DIRECTION_SIMPLE>",
    "<T_DIRECTION>",
    "<T_ORIENTATION>",
    "<LST_DIRECTION>",
    "<NUMBER>",
    "<DIGIT>",
    "<VAR>",
    "\",\"",
  };

}
