/* Generated By:JavaCC: Do not edit this line. ParserCAMLConstants.java */
package uniandes.teolen.parserJavaCC.myParser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserCAMLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PP = 5;
  /** RegularExpression Id. */
  int INT = 6;
  /** RegularExpression Id. */
  int DIGIT = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"::\"",
    "<INT>",
    "<DIGIT>",
    "\"@\"",
    "\"[\"",
    "\",\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
  };

}
