// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/TestPerm001.gold"
import gold.*;
import gold.structures.*;
import gold.structures.automaton.*;
import gold.structures.bag.*;
import gold.structures.collection.*;
import gold.structures.deque.*;
import gold.structures.disjointset.*;
import gold.structures.graph.*;
import gold.structures.heap.*;
import gold.structures.list.*;
import gold.structures.map.*;
import gold.structures.multimap.*;
import gold.structures.point.*;
import gold.structures.queue.*;
import gold.structures.set.*;
import gold.structures.stack.*;
import gold.structures.tree.*;
import gold.structures.tree.binary.*;
import gold.structures.tree.nary.*;
import gold.structures.tuple.*;
import gold.structures.turingMachine.*;
import gold.swing.*;
import gold.swing.icon.*;
import gold.swing.icon.ajaxload.*;
import gold.swing.icon.famfamfam.*;
import gold.swing.icon.gold.*;
import gold.swing.icon.jlfgr.*;
import gold.swing.icon.wikimedia.*;
import gold.swing.icon.windows.*;
import gold.swing.look.*;
import gold.swing.util.*;
import gold.test.*;
import gold.test.automaton.*;
import gold.test.general.*;
import gold.test.graph.*;
import gold.util.*;
import gold.visualization.*;
import gold.visualization.automaton.*;
import gold.visualization.graph.*;
import gold.visualization.quadtree.*;
import gold.visualization.turingMachine.*;
import gold.visualization.util.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class TestPerm001 {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static Object A=null;
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=25;
      if ($opEqualY($invokeField("length",args),0)) {
        $line=25;
        A=$fix($opIntvlY('a','c'));
      }
      else {
        $line=27;
        gold.structures.set.ISet $v1=$newSet();
        int $v3=$int(0);
        int $v4=$int($invokeMethod("length",((java.lang.String[])args)[$int(0)],new Object[]{}))-1;
        $v2:for (int i=$v3; i<=$v4; i++) {
          $v1.add($invokeMethod("charAt",((java.lang.String[])args)[$int(0)],new Object[]{i}));
        }
        A=$fix($v1);
      }
      $line=30;
      $invokeMethod(TestPerm001.class,"testPerm",true,null,new Object[]{$invokeMethod(TestPerm001.class,"create",true,null,new Object[]{})});
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,TestPerm001.class,"main",$line);
    }
  }
  public static IAutomaton create() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=37;
      Object Q=$fix($opUnionY($opCartsY(new Object[]{$opPwsetY(A),$opIntvlY(1,2)}),GCollections.asSet(0)));
      $line=38;
      Object \u03A3=$fix($opUnionY(A,GCollections.asSet('$')));
      $line=39;
      Object q_0=$fix(GCollections.asList(GCollections.emptySet(),1));
      $line=40;
      Object F=$fix(GCollections.asSet(GCollections.asList(GCollections.emptySet(),2)));
      $line=41;
      $result=$invokeConstructor(GDeterministicAutomaton.class,new Object[]{Q,\u03A3,q_0,F,new GMethod(TestPerm001.class,"delta")});
      if (true) break $try;
      $line=42;
      $rethrow(new RuntimeException("The function \"create()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,TestPerm001.class,"create",$line);
    }
    return $cast(IAutomaton.class,$result);
  }
  public static Object delta(Object q, Object s) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=45;
      $result=q;
      if (true) break $try;
      $line=46;
      $rethrow(new RuntimeException("The function \"delta(q:Object,s:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,TestPerm001.class,"delta",$line);
    }
    return $result;
  }
  public static Object delta(java.lang.Iterable $v5, Object s) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v6=GCollections.unmodifiableCollection($v5).iterator();
      Object q=$v6.next();
      Object p=$v6.next();
      $line=49;
      if (($opEqualY(p,1)&&$opEqualY(s,'$'))) {
        $line=49;
        $result=GCollections.asList(q,2);
        if (true) break $try;
      }
      else {
        $line=50;
        if ($opEqualY(s,'$')) {
          $line=50;
          $result=0;
          if (true) break $try;
        }
        else {
          $line=51;
          if (($opEqualY(p,1)&&$opMembrY(s,q))) {
            $line=51;
            $result=0;
            if (true) break $try;
          }
          else {
            $line=52;
            if ($opEqualY(p,1)) {
              $line=52;
              $result=GCollections.asList($opUnionY(q,GCollections.asSet(s)),1);
              if (true) break $try;
            }
            else {
              $line=53;
              if ($opMembrY(s,q)) {
                $line=53;
                $result=GCollections.asList($opDiffeY(q,GCollections.asSet(s)),2);
                if (true) break $try;
              }
              else {
                $line=54;
                $result=0;
                if (true) break $try;
              }
            }
          }
        }
      }
      $line=57;
      $rethrow(new RuntimeException("The function \"delta(\u27E8q,p\u27E9:java.lang.Iterable,s:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,TestPerm001.class,"delta",$line);
    }
    return $result;
  }
  public static Object testPerm(IAutomaton C) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=60;
      java.util.Scanner sc=null;
      sc=$invokeConstructor(java.util.Scanner.class,new Object[]{$invokeField(System.class,"in",true,null)});
      $line=61;
      String string=null;
      string=$defaultValue(String.class);
      $line=64;
      System.out.println($message(new Object[]{"Testing"}));
      $line=65;
      while (true) {
        if (!($bool(true))) break;
        $line=66;
        System.out.println($message(new Object[]{"----------------------------"}));
        $line=67;
        System.out.println($message(new Object[]{"Enter a string:"}));
        $line=68;
        string=$cast(String.class,$fix(((java.util.Scanner)sc).nextLine()));
        $line=69;
        if ($opEqualY(string,"")) {
          $line=69;
          break;
        }
        $line=70;
        Object result=$fix(((gold.structures.automaton.IAutomaton)C).acceptsString($cast(java.lang.String.class,string)));
        $line=71;
        System.out.println($message(new Object[]{$opAdditY("The string was ",(($bool(result))?("accepted"):("REJECTED")))}));
      }
      $line=73;
      System.out.println($message(new Object[]{"End test"}));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,TestPerm001.class,"testPerm",$line);
    }
    return $result;
  }
}
