// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/asandbsNONDET.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class asandbsNONDET {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static Object getName() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=16;
      $result="#a=#b";
      if (true) break $try;
      $line=17;
      $rethrow(new RuntimeException("The function \"getName()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,asandbsNONDET.class,"getName",$line);
    }
    return $result;
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=21;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,asandbsNONDET.createAutomaton()));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,asandbsNONDET.class,"main",$line);
    }
  }
  public static IPushdownAutomaton createAutomaton() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=24;
      Object \u03A3=$fix($opIntvlY('a','b'));
      $line=26;
      Object Q=$fix(GCollections.asSet(1));
      $line=28;
      Object \u0393=$fix(GCollections.asSet('a','b'));
      $line=29;
      Object q_0=$fix(1);
      $line=30;
      Object F=$fix(GCollections.asSet(1));
      $line=31;
      Object M=$fix($invokeConstructor(GPushdownAutomaton.class,new Object[]{Q,\u03A3,\u0393,q_0,F}));
      $line=33;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,1,$cast(java.lang.String.class,"a")),new Object[]{"a"});
      $line=34;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,1,$cast(java.lang.String.class,"a")),new Object[]{"b"});
      $line=35;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,1,$cast(java.lang.String.class,"b")),new Object[]{"b"});
      $line=36;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,1,$cast(java.lang.String.class,"b")),new Object[]{"a"});
      $line=40;
      $result=M;
      if (true) break $try;
      $line=41;
      $rethrow(new RuntimeException("The function \"createAutomaton()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,asandbsNONDET.class,"createAutomaton",$line);
    }
    return $cast(IPushdownAutomaton.class,$result);
  }
}
