// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/divisionEqualsProduct.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class divisionEqualsProduct {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=16;
      divisionEqualsProduct.testAutomaton($cast(gold.structures.automaton.IAutomaton.class,divisionEqualsProduct.createAutomaton()));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,divisionEqualsProduct.class,"main",$line);
    }
  }
  public static IPushdownAutomaton createAutomaton() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=20;
      Object \u03A3=$fix(GCollections.asSet('x','\u00F7','3','5','7','=','q','\u00D7','+','r'));
      $line=21;
      Object Q=$fix(GCollections.asSet('$','I','F','3','5','7'));
      $line=22;
      Object \u0393=$fix(GCollections.asSet('1','$'));
      $line=23;
      Object q_0=$fix('$');
      $line=24;
      Object F=$fix(GCollections.asSet('F'));
      $line=25;
      Object M=$fix($invokeConstructor(GPushdownAutomaton.class,new Object[]{Q,\u03A3,\u0393,q_0,F}));
      $line=27;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta('$','I',$cast(java.lang.String.class,"")),new Object[]{"$"});
      $line=28;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta('I','I',$cast(java.lang.String.class,'x')),new Object[]{"1"});
      $line=29;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta('I','I',$cast(java.lang.String.class,'\u00F7')),new Object[]{});
      $line=30;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta('I','3',$cast(java.lang.String.class,'3')),new Object[]{});
      $line=31;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta('I','5',$cast(java.lang.String.class,'5')),new Object[]{});
      $line=32;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta('I','7',$cast(java.lang.String.class,'7')),new Object[]{});
      $line=33;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta('3','3',$cast(java.lang.String.class,'=')),new Object[]{});
      $line=34;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta('5','5',$cast(java.lang.String.class,'=')),new Object[]{});
      $line=35;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta('7','7',$cast(java.lang.String.class,'=')),new Object[]{});
      $line=36;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta('3','3',$cast(java.lang.String.class,'q')),new Object[]{"111"});
      $line=37;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta('5','5',$cast(java.lang.String.class,'q')),new Object[]{"11111"});
      $line=38;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta('7','7',$cast(java.lang.String.class,'q')),new Object[]{"1111111"});
      $line=39;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta('3','3',$cast(java.lang.String.class,'\u00D7')),new Object[]{});
      $line=40;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta('5','5',$cast(java.lang.String.class,'\u00D7')),new Object[]{});
      $line=41;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta('7','7',$cast(java.lang.String.class,'\u00D7')),new Object[]{});
      $line=42;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta('3','I',$cast(java.lang.String.class,'3')),new Object[]{});
      $line=43;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta('5','I',$cast(java.lang.String.class,'5')),new Object[]{});
      $line=44;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta('7','I',$cast(java.lang.String.class,'7')),new Object[]{});
      $line=45;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta('I','I',$cast(java.lang.String.class,'+')),new Object[]{});
      $line=46;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta('I','I',$cast(java.lang.String.class,'r')),new Object[]{"1"});
      $line=47;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta('I','F',$cast(java.lang.String.class,"")),new Object[]{"$"});
      $line=49;
      $result=M;
      if (true) break $try;
      $line=50;
      $rethrow(new RuntimeException("The function \"createAutomaton()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,divisionEqualsProduct.class,"createAutomaton",$line);
    }
    return $cast(IPushdownAutomaton.class,$result);
  }
  public static Object testAutomaton(IAutomaton C) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=53;
      java.util.Scanner sc=null;
      sc=$invokeConstructor(java.util.Scanner.class,new Object[]{$invokeField(System.class,"in",true,null)});
      $line=54;
      String string=null;
      string=$defaultValue(String.class);
      $line=56;
      System.out.println($message(new Object[]{"Stack Automaton Ready"}));
      $line=58;
      while (true) {
        if (!($bool(true))) break;
        $line=59;
        System.out.println($message(new Object[]{"----------------------------"}));
        $line=60;
        System.out.println($message(new Object[]{"Enter a string:"}));
        $line=61;
        string=$cast(String.class,$fix(((java.util.Scanner)sc).nextLine()));
        $line=62;
        if ($opEqualY(string,"STOP")) {
          $line=62;
          break;
        }
        $line=63;
        Object result=$fix(((gold.structures.automaton.IAutomaton)C).acceptsString($cast(java.lang.String.class,string)));
        $line=64;
        System.out.println($message(new Object[]{$opAdditY("The string was ",(($bool(result))?("accepted"):("REJECTED")))}));
      }
      $line=66;
      System.out.println($message(new Object[]{"End test"}));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,divisionEqualsProduct.class,"testAutomaton",$line);
    }
    return $result;
  }
}
