// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/FuncsGramBottomUp.gold"
import gold.*;
import gold.structures.*;
import gold.structures.automaton.*;
import gold.structures.bag.*;
import gold.structures.collection.*;
import gold.structures.deque.*;
import gold.structures.disjointset.*;
import gold.structures.graph.*;
import gold.structures.heap.*;
import gold.structures.list.*;
import gold.structures.map.*;
import gold.structures.multimap.*;
import gold.structures.point.*;
import gold.structures.queue.*;
import gold.structures.set.*;
import gold.structures.stack.*;
import gold.structures.tree.*;
import gold.structures.tree.binary.*;
import gold.structures.tree.nary.*;
import gold.structures.tuple.*;
import gold.structures.turingMachine.*;
import gold.swing.*;
import gold.swing.icon.*;
import gold.swing.icon.ajaxload.*;
import gold.swing.icon.famfamfam.*;
import gold.swing.icon.gold.*;
import gold.swing.icon.jlfgr.*;
import gold.swing.icon.wikimedia.*;
import gold.swing.icon.windows.*;
import gold.swing.look.*;
import gold.swing.util.*;
import gold.test.*;
import gold.test.automaton.*;
import gold.test.general.*;
import gold.test.graph.*;
import gold.util.*;
import gold.visualization.*;
import gold.visualization.automaton.*;
import gold.visualization.graph.*;
import gold.visualization.quadtree.*;
import gold.visualization.turingMachine.*;
import gold.visualization.util.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class FuncsGramBottomUp {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static Object A=null;
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=19;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,FuncsGramBottomUp.create()));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,FuncsGramBottomUp.class,"main",$line);
    }
  }
  public static IAutomaton create() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=27;
      Object Q=$fix(GCollections.asSet("q","s","f"));
      $line=28;
      Object \u03A3=$fix(GCollections.asSet('n','f',',','(',')'));
      $line=29;
      Object \u0393=$fix($opUnionY(\u03A3,GCollections.asSet('$','E','L')));
      $line=30;
      Object q_0=$fix("s");
      $line=31;
      Object F=$fix(GCollections.asSet("f"));
      $line=34;
      Object M=$fix($invokeConstructor(GPushdownAutomaton.class,new Object[]{Q,\u03A3,\u0393,q_0,F}));
      $line=36;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta("s","q",$cast(java.lang.String.class,"")),new Object[]{"$"});
      $line=37;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("q","f",$cast(java.lang.String.class,"")),new Object[]{"$E"});
      $line=39;
      for (Object $v1:GCollections.unmodifiableCollection(\u03A3)) {
        Object t=$v1;
        $line=40;
        $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta("q","q",$cast(java.lang.String.class,t)),new Object[]{$opAdditY("",t)});
      }
      $line=43;
      $invokeMethod("changeTop",((gold.structures.automaton.GPushdownAutomaton)M).delta("q","q",$cast(java.lang.String.class,"")),new Object[]{"n","E"});
      $line=44;
      $invokeMethod("changeTop",((gold.structures.automaton.GPushdownAutomaton)M).delta("q","q",$cast(java.lang.String.class,"")),new Object[]{"f(L)","E"});
      $line=45;
      $invokeMethod("changeTop",((gold.structures.automaton.GPushdownAutomaton)M).delta("q","q",$cast(java.lang.String.class,"")),new Object[]{"E","L"});
      $line=46;
      $invokeMethod("changeTop",((gold.structures.automaton.GPushdownAutomaton)M).delta("q","q",$cast(java.lang.String.class,"")),new Object[]{"L,E","L"});
      $line=53;
      $result=M;
      if (true) break $try;
      $line=54;
      $rethrow(new RuntimeException("The function \"create()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,FuncsGramBottomUp.class,"create",$line);
    }
    return $cast(IAutomaton.class,$result);
  }
  public static Object testAutomaton(IAutomaton C) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=60;
      java.util.Scanner sc=null;
      sc=$invokeConstructor(java.util.Scanner.class,new Object[]{$invokeField(System.class,"in",true,null)});
      $line=61;
      String string=null;
      string=$defaultValue(String.class);
      $line=64;
      System.out.println($message(new Object[]{"Testing"}));
      $line=66;
      while (true) {
        if (!($bool(true))) break;
        $line=67;
        System.out.println($message(new Object[]{"----------------------------"}));
        $line=68;
        System.out.println($message(new Object[]{"Enter a string:"}));
        $line=69;
        string=$cast(String.class,$fix(((java.util.Scanner)sc).nextLine()));
        $line=70;
        if ($opEqualY(string,"STOP")) {
          $line=70;
          break;
        }
        $line=71;
        Object result=$fix(((gold.structures.automaton.IAutomaton)C).acceptsString($cast(java.lang.String.class,string)));
        $line=72;
        System.out.println($message(new Object[]{$opAdditY("The string was ",(($bool(result))?("accepted"):("REJECTED")))}));
      }
      $line=74;
      System.out.println($message(new Object[]{"End test"}));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,FuncsGramBottomUp.class,"testAutomaton",$line);
    }
    return $result;
  }
}
