// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/Stickmath.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class Stickmath {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=18;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,Stickmath.createAutomaton()));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Stickmath.class,"main",$line);
    }
  }
  public static IPushdownAutomaton createAutomaton() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=21;
      Object \u03A3=$fix(GCollections.asSet('1','+','-','=','0'));
      $line=23;
      Object Q=$fix(GCollections.asSet(0,1,2,4,5,7,8,9));
      $line=25;
      Object \u0393=$fix(GCollections.asSet('$','1'));
      $line=26;
      Object q_0=$fix(0);
      $line=27;
      Object F=$fix(GCollections.asSet(9));
      $line=28;
      Object M=$fix($invokeConstructor(GPushdownAutomaton.class,new Object[]{Q,\u03A3,\u0393,q_0,F}));
      $line=30;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,1,$cast(java.lang.String.class,"")),new Object[]{"$"});
      $line=32;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,2,$cast(java.lang.String.class,"1")),new Object[]{"1"});
      $line=33;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,2,$cast(java.lang.String.class,"1")),new Object[]{"1"});
      $line=34;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,4,$cast(java.lang.String.class,"+1")),new Object[]{"1"});
      $line=35;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,7,$cast(java.lang.String.class,"-1")),new Object[]{"1"});
      $line=37;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(4,4,$cast(java.lang.String.class,"1")),new Object[]{"1"});
      $line=38;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(4,5,$cast(java.lang.String.class,"=1")),new Object[]{"1"});
      $line=39;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,5,$cast(java.lang.String.class,"1")),new Object[]{"1"});
      $line=40;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,9,$cast(java.lang.String.class,"")),new Object[]{"$"});
      $line=44;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(7,7,$cast(java.lang.String.class,"1")),new Object[]{"1"});
      $line=45;
      $invokeMethod("pushOn",((gold.structures.automaton.GPushdownAutomaton)M).delta(7,8,$cast(java.lang.String.class,"1")),new Object[]{"$","1"});
      $line=47;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(7,5,$cast(java.lang.String.class,"=1")),new Object[]{"1"});
      $line=49;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(8,8,$cast(java.lang.String.class,"1")),new Object[]{"1"});
      $line=50;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(8,5,$cast(java.lang.String.class,"=-1")),new Object[]{"1"});
      $line=53;
      $result=M;
      if (true) break $try;
      $line=54;
      $rethrow(new RuntimeException("The function \"createAutomaton()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Stickmath.class,"createAutomaton",$line);
    }
    return $cast(IPushdownAutomaton.class,$result);
  }
}
