// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/wcrev_w.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class wcrev_w {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=15;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,wcrev_w.createAutomaton()));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,wcrev_w.class,"main",$line);
    }
  }
  public static IPushdownAutomaton createAutomaton() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=18;
      Object \u03A3=$fix($opIntvlY('a','c'));
      $line=20;
      Object Q=$fix(GCollections.asSet(1,2));
      $line=22;
      Object \u0393=$fix(\u03A3);
      $line=23;
      Object q_0=$fix(1);
      $line=24;
      Object F=$fix(GCollections.asSet(1,2));
      $line=25;
      Object M=$fix($invokeConstructor(GPushdownAutomaton.class,new Object[]{Q,\u03A3,\u0393,q_0,F}));
      $line=27;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,1,$cast(java.lang.String.class,"a")),new Object[]{"a"});
      $line=28;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,1,$cast(java.lang.String.class,"b")),new Object[]{"b"});
      $line=30;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,2,$cast(java.lang.String.class,"c")),new Object[]{});
      $line=31;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,2,$cast(java.lang.String.class,"b")),new Object[]{"b"});
      $line=32;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,2,$cast(java.lang.String.class,"a")),new Object[]{"a"});
      $line=36;
      $result=M;
      if (true) break $try;
      $line=37;
      $rethrow(new RuntimeException("The function \"createAutomaton()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,wcrev_w.class,"createAutomaton",$line);
    }
    return $cast(IPushdownAutomaton.class,$result);
  }
}
